# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c28d68088a62c90be6561c2dc42dc4f18c3e046fb5f76f9a5b3e2d2fc594025b09158063b9c8a9ea0e5cd5b2d69b3d6cb39c5fe57ae1fb7c7b46d377659788e

test:
  secret_key_base: 853cf6b60ad549524181de8515cf1af247aeb2603b2442f87a54ffcd4e69aef6b611e14434b74ca2f3efd4939f46ddc5c582c4399bebe6e693bc42126fb5a70b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
